### ISSUE TITLE
GetTor landing page

### ISSUE THREAD

**Issue by ilv** [TheTorProject/gettor#15]
This is related to [this ticket](https://github.com/TheTorProject/gettorbrowser/issues/1), and it basically proposes to create a landing page on github where people can find links to download Tor Browser, aimed for places where [Tor Project's website](https://www.torproject.org) is blocked. I have made a sample page on the gh-pages branch of this repo, you can view it [here](https://thetorproject.github.io/gettor). It is based on [Psiphon landing page](https://psiphon3.com/en/download.html).

Thoughts? @azadi @DonnchaC @aagbsn @mrphs

**Comment by azadi** [comment]
:+1: from me!

**Comment by DonnchaC** [comment]
+1 too, looks good!

**Comment by ilv** [comment]
Ok, so I've created a [script](https://gitweb.torproject.org/gettor.git/tree/create_gh_mirrors.py) to automatically update the [README file](https://github.com/TheTorProject/gettorbrowser/blob/master/README.md) of gettorbrowser and this [landing page](https://thetorproject.github.io/gettor).

**Comment by DonnchaC** [comment]
:+1:  Awesome work llv! 

One small change would be to list the language options in the native language rather than in English (e.g Русский and فارسی. 

I also think it would be very useful to provide some information about the gettor@torproject.org and bridges@torproject.org services. It could provide a fallback for users who can access Github page but not the TorProject.org or the downloads on https://github-cloud.s3.amazonaws.com.

Have you asked the TPO website team to link to https://github.com/TheTorProject/gettorbrowser? It would be a good first step in getting the Github indexed and findable by users. Again great stuff!

**Comment by DonnchaC** [comment]
It would also be great to include a link to and Orbot APK and Google Play store. Maybe the Guardian Project can also link back to this Tor Browser mirror from their Play store page?

**Comment by ilv** [comment]
thanks @DonnchaC!

I thought it would be better to enable language options once we have the content of the website translated, but I guess we could do something similar to what we do with the gettor bot for the moment (provide localized bundle). Adding instructions to reach the gettor and bridges email bots sounds good, will do! and I will also talk to the website team to see what they think.

With respect to Orbot, I'm currently working on it and it should soon be ready to add it to the list of downloads.

Thanks for all the feedback!
